//------------------------------------------------------------------------------
// <auto-generated>
namespace DTO
{
    using System;
    using System.Collections.Generic;
    using DAL;
    public class AmutaConvertion
    {
        public static AmutaDto convertToDto(Amuta amuta)
        {
            AmutaDto newAmuta = new AmutaDto();
        //    newAmuta.Amuta_deposits = amuta.Amuta_deposits;
            newAmuta.id_amuta = amuta.id_amuta;
            newAmuta.name_amuta = amuta.name_amuta;
            newAmuta.ribit = amuta.ribit;
      
            return newAmuta;
        }

        public static List<AmutaDto> convertToListDto(List<Amuta> amuta)
        {

            List<AmutaDto> newAmuta = new List<AmutaDto>();
            amuta.ForEach(x =>
            {
                newAmuta.Add(convertToDto(x));
            });
            return newAmuta;
        }

        public static Amuta convertToAmuta(AmutaDto amuta)
        {
            Amuta newAmuta = new Amuta();
          //  newAmuta.Amuta_deposits = amuta.Amuta_deposits;
            newAmuta.id_amuta = amuta.id_amuta;
            newAmuta.name_amuta = amuta.name_amuta;
            newAmuta.ribit = amuta.ribit;

            return newAmuta;

        }

    }

}
