//------------------------------------------------------------------------------
// <auto-generated>
namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public  class AmutaDto
    {
        public AmutaDto()
        {
           
        }
    
        public int id_amuta { get; set; }
        public string name_amuta { get; set; }
        public double ribit { get; set; }
        public  List<Amuta_depositsDto> Amuta_deposits { get; set; }
    }
}
