//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Amuta_deposits = new HashSet<Amuta_deposits>();
            this.Loans = new HashSet<Loans>();
            this.User_expense = new HashSet<User_expense>();
            this.User_income = new HashSet<User_income>();
        }
    
        public string id_user { get; set; }
        public string name_user { get; set; }
        public string tel { get; set; }
        public int misgeret { get; set; }
        public string email { get; set; }
        public Nullable<int> id_amuta { get; set; }
        public bool is_admin { get; set; }
        public bool is_disabled { get; set; }
    
        public virtual Amuta Amuta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Amuta_deposits> Amuta_deposits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Loans> Loans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_expense> User_expense { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_income> User_income { get; set; }
    }
}
