//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_expense
    {
        public int id { get; set; }
        public int id_expense { get; set; }
        public int id_kind { get; set; }
        public string id_user { get; set; }
        public int sum { get; set; }
        public System.DateTime expense_date { get; set; }
        public string expense_info { get; set; }
    
        public virtual Expenses Expenses { get; set; }
        public virtual Kinds Kinds { get; set; }
        public virtual User User { get; set; }
    }
}
